---
title: "To prepare Github raw data"
author: "Taeyoung Hwang, Jan 5, 2023"
output: github_document
---

# 1. PUM2

```{r}
rm(list=ls())
load("~/Research/MPRNA/2.Manuscript/final_PUM2_pipeline.Rdata")

count.table$rpm <- count.table$raw / (fastqc$CountedNum[match(count.table$sample, fastqc$Sample)]/10^6)
```

```{r}
fastqc$Sample <- fastqc$FileName
fastqc$Repl <- fastqc$Replicate
fastqc$SampleID <- paste(fastqc$Repl, fastqc$Pulldown, sep="_")
fastqc$NumReads <- fastqc$TotalReadNum
fastqc$GC. <- fastqc$GCpct
fastqc$UnmappedRate <- fastqc$UnmappedProp
fastqc <- fastqc[, c("SampleID", "Repl", "Pulldown", "CountedNum")]
```

```{r}
oligo.count <- count.table; rm(count.table)
oligo.count$repl <- oligo.count$replicate
oligo.count <- oligo.count[, c("tileID", "barcodeID", "repl", "pulldown", "raw", "rpm")]
rownames(oligo.count) <- 1:nrow(oligo.count)
```

```{r}
tile.annot <- tile.table; rm(tile.table)
tile.annot <- tile.annot[, 1:12]
```

```{r}
save(fastqc, oligo.count, tile.annot, file = "~/Research/MPRNA/2.Manuscript/Git2/RawData/git_PUM2_raw.Rdata")
```

# 2. MS2-MCP, NAR Revision 2
```{r}
rm(list=ls())

load("~/Research/MPRNA/2.Manuscript/final_4xMS2_pipeline2.Rdata")

tile.annot$tileID <- as.character(tile.annot$tileID)
oligo.count$tileID <- gsub("ms2-4x_", "ms2-4x:", oligo.count$tileID)
```

Stem mutation table
```{r}
# stem design
stem.design <- read.table("~/Research/MPRNA/1.Project/MS2/1.Design/ms2_mt_stem.txt", header=T, sep="\t", stringsAsFactors = F)
stem.design$stemID <- paste(stem.design$idx, stem.design$mutation, sep="_")

# map to tileID
temp <- subset(tile.annot, group=="Stem")
temp$stemID <- paste(temp$mutLoc, temp$mutType, sep="_")
stem.design$tileID <- temp$tileID[match(stem.design$stemID, temp$stemID)]

# assign tileID of duplicated sequence
temp <- split(stem.design, f = stem.design$seq)
temp <- lapply(temp, function(x) {idx <- which(!is.na(x$tileID)); if (length(idx==1)) {x$tileID<-x$tileID[idx]; return(x)} else {cat("Error"); return(0)}})
stem.design <- do.call(rbind, temp)
rownames(stem.design) <- 1:nrow(stem.design)

# table
stem.table <- dcast(stem.design, idx~mutation, value.var = "tileID")
colnames(stem.table) <- c("stemID", "tileID.mut3p", "tileID.mut5p", "tileID.comp")
stem.table$tileID.wt <- subset(tile.annot, group=="WT")$tileID

stem.table <- stem.table[order(as.numeric(gsub("stem:", "", stem.table$stemID))), ]
```

```{r}
fastqc <- fastqc[, c("SampleID", "Repl", "Pulldown", "CountedNum")]
save(fastqc, tile.annot, oligo.count, stem.table, file = "~/Research/MPRNA/2.Manuscript/Git2/RawData/git_ms2_raw.Rdata")
```

# 3. hTR-FLAG-hTERT
```{r}
rm(list=ls())
load("~/Research/MPRNA/2.Manuscript/final_hTR_pipeline2.Rdata") # fastqc, oligo.count, tile.annot, tile.rpm, tile.table

oligo.count$tileID <- as.character(oligo.count$tileID)
oligo.count <- oligo.count[, c("tileID", "barcodeID", "repl", "pulldown", "raw", "rpm")]
rownames(oligo.count) <- 1:nrow(oligo.count)
```

```{r}
fastqc <- fastqc[, c("SampleID", "Repl", "Pulldown", "CountedNum")]
save(fastqc, tile.annot, oligo.count, file = "~/Research/MPRNA/2.Manuscript/Git2/RawData/git_hTR_raw.Rdata")
```

# 4. CTCF

```{r}
rm(list=ls())
load("~/Research/MPRNA/2.Manuscript/final_CTCF_pipeline.Rdata")
```

```{r}
tile.annot <- read.table("~/Research/MPRNA/1.Project/CTCF/ctcf_annot.txt", sep="\t", header=T, stringsAsFactors = F)
tile.annot <- tile.annot[, c(1,2,3,4,5,6,19,26)]
```

```{r}
fastqc <- fastqc[, c("SampleID", "Repl", "Pulldown", "CountedNum")]
save(fastqc, oligo.count, tile.annot, file = "~/Research/MPRNA/2.Manuscript/Git2/RawData/git_CTCF_raw.Rdata")
```

# 5. WRAP53
```{r}
rm(list=ls())
load("~/Research/MPRNA/Batch_51/batch51_pipeline.Rdata") # fastqc, oligo.count, tile.table, tile.rpm
fastqc <- subset(fastqc, Sorting=="SPH")
oligo.count <- subset(oligo.count, sorting=="SPH")

tile.annot <- read.table("~/Research/MPRNA/1.Project/WRAP53mt/wrap53mt_design.txt", sep="\t", header=T)
```

```{r}
# fastqc
fastqc$Pulldown <- rep(c("Input", "IP"), 3)
fastqc$Repl <- fastqc$Rep
fastqc$SampleID <- paste(fastqc$Rep, fastqc$Pulldown, sep="_")

fastqc <- fastqc[, c("Sample", "SampleID", "Repl", "Pulldown", "NumReads", "Length", "CountedNum")]

# oligo.count
oligo.count$pulldown <- gsub("FlagCTCF", "IP" , oligo.count$pulldown)
oligo.count$repl <- oligo.count$rep
oligo.count <- oligo.count[, c("tileID", "barcodeID", "repl", "pulldown", "raw", "rpm")]
rownames(oligo.count) <- 1:nrow(oligo.count)

# annotation
tile.annot$seq <- NULL
table(tile.annot$type, tile.annot$mutation)

save(fastqc, oligo.count, tile.annot, file = "~/Research/MPRNA/2.Manuscript/Git2/RawData/git_WRAP53_raw.Rdata")
```


